# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAhJnOlr6jzTtCCRTcQAccHdPi8Yj0Kc
"""

import string

mybook=open("book.txt","r")
lines=mybook.readlines()

for i in lines:
  a=i.split(' ')
  for j in a:
    b=j.strip(string.punctuation)
    print(b.lower())